---
- name: Deploy to K8s Cluster
  hosts: localhost
  connection: local
  become: true
  tasks:
  - name: Deploy Pod
    shell: |
      /usr/local/bin/kubectl apply -f deployment.yaml

  - name: Deploy Service
    shell: |
      /usr/local/bin/kubectl apply -f service.yaml
