kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: dotnet-ingress
spec:
  rules:
  - host: host.example.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
             name: dotnet-demo-service
             port:
               number: 80
